-- Decoy seed — generates realistic-looking vault/wallet/proof rows with
-- cryptographically random keys, staggered timestamps, and synthetic
-- mint/burn/transfer history.
--
-- Operator workflow:
--   1. Run this migration once per deployment.
--   2. Immediately run: \copy seeded_identifiers TO 'watchlist.txt' CSV
--      and store watchlist.txt OFF the edge host (not in this repo).
--   3. Set EDGE_WATCHLIST_FILE to that path on the edge host so the tripwire
--      can flag attempts to interact with these identifiers.
--   4. DROP TABLE seeded_identifiers; (so the edge DB itself does not
--      retain a list of which IDs are bait).
--
-- Rationale: every identifier here is functionally a canary — but it is
-- shaped like real production data (random hex, plausible prefixes), so an
-- attacker reading the DB cannot distinguish bait from "real" rows. The
-- only canonical list is the operator's off-host watchlist.txt.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Holds the IDs/addresses generated by this migration so the operator can
-- export them once and then drop the table. NOT a permanent record.
CREATE TABLE IF NOT EXISTS seeded_identifiers (
    kind  TEXT NOT NULL,
    value TEXT NOT NULL
);

DO $seed$
DECLARE
    i             INTEGER;
    n_decoys      INTEGER := 24;
    base_age_days INTEGER;
    created_ts    TIMESTAMPTZ;
    vault_id      TEXT;
    user_id       TEXT;
    wallet_id     TEXT;
    wallet_addr   TEXT;
    deposit_addr  TEXT;
    mast_addr     TEXT;
    pk_hex        TEXT;
    kyber_pk_hex  TEXT;
    taproot_sk    TEXT;
    taproot_pk    TEXT;
    btc_sats      BIGINT;
    ubtc_minted   NUMERIC;
    btc_price     NUMERIC := 60000 + (random() * 20000)::NUMERIC;
    username      TEXT;
    email         TEXT;
    wallet_name   TEXT;
    j             INTEGER;
    mint_id       TEXT;
    burn_id       TEXT;
    transfer_id   TEXT;
    mint_amt      NUMERIC;
    burn_amt      NUMERIC;
    proof_id      TEXT;
    proof_db_id   TEXT;
    nullifier_id  TEXT;
    nullifier_hex TEXT;
BEGIN
    FOR i IN 1..n_decoys LOOP
        base_age_days := (random() * 270)::INTEGER;
        created_ts    := NOW() - (base_age_days * INTERVAL '1 day') - (random() * INTERVAL '23 hours');

        vault_id     := 'vault_' || substr(encode(gen_random_bytes(4), 'hex'), 1, 8);
        user_id      := 'usr_'   || substr(encode(gen_random_bytes(4), 'hex'), 1, 8);
        wallet_id    := 'wal_'   || substr(encode(gen_random_bytes(4), 'hex'), 1, 8);
        wallet_addr  := 'ubtc1'  || substr(encode(gen_random_bytes(16), 'hex'), 1, 32);
        deposit_addr := 'bcrt1p' || substr(encode(gen_random_bytes(32), 'hex'), 1, 58);
        mast_addr    := 'bcrt1p' || substr(encode(gen_random_bytes(32), 'hex'), 1, 58);

        -- ML-DSA-65 PK is 1952 bytes. Real-looking high-entropy hex.
        pk_hex       := encode(gen_random_bytes(1952), 'hex');
        kyber_pk_hex := encode(gen_random_bytes(1568), 'hex');     -- ML-KEM-1024 PK
        taproot_sk   := encode(gen_random_bytes(32), 'hex');
        taproot_pk   := (CASE WHEN random() < 0.5 THEN '02' ELSE '03' END)
                        || substr(encode(gen_random_bytes(32), 'hex'), 1, 64);

        btc_sats     := ((10 + random() * 50)::NUMERIC * 1e7)::BIGINT;
        ubtc_minted  := round((btc_sats / 1e8 * btc_price * (0.55 + random() * 0.20))::NUMERIC, 2);

        username     := (CASE
                          WHEN random() < 0.25 THEN 'treasury_'
                          WHEN random() < 0.5  THEN 'wallet_'
                          WHEN random() < 0.75 THEN 'user_'
                          ELSE 'cold_'
                         END) || substr(encode(gen_random_bytes(3), 'hex'), 1, 6);
        email        := username || '@' || (CASE
                          WHEN random() < 0.3  THEN 'protonmail.com'
                          WHEN random() < 0.6  THEN 'gmail.com'
                          WHEN random() < 0.85 THEN 'tutanota.com'
                          ELSE 'mail.local'
                         END);
        wallet_name  := (CASE
                          WHEN random() < 0.2 THEN 'Hot Wallet'
                          WHEN random() < 0.4 THEN 'Treasury'
                          WHEN random() < 0.6 THEN 'Cold Storage'
                          WHEN random() < 0.8 THEN 'Daily'
                          ELSE 'Reserve'
                         END);

        INSERT INTO ubtc_users (id, username, email, wallet_address, created_at)
        VALUES (user_id, username, email, wallet_addr, created_ts)
        ON CONFLICT DO NOTHING;

        INSERT INTO ubtc_wallets (
            id, user_id, wallet_address, wallet_name, public_key, kyber_pk,
            balance, linked_vault_id, created_at, updated_at
        ) VALUES (
            wallet_id, user_id, wallet_addr, wallet_name, pk_hex, kyber_pk_hex,
            ubtc_minted::TEXT, vault_id,
            created_ts, created_ts + (random() * INTERVAL '12 hours')
        )
        ON CONFLICT DO NOTHING;

        INSERT INTO vaults (
            id, deposit_address, user_pubkey, internal_key,
            btc_amount_sats, ubtc_minted, status, network, account_type,
            mast_address, taproot_pubkey, taproot_secret_key,
            utxo_txid, confirmations, confirmed_at, created_at
        ) VALUES (
            vault_id, deposit_addr, pk_hex, pk_hex,
            btc_sats, ubtc_minted::TEXT, 'active', 'regtest', 'current',
            mast_addr, taproot_pk, taproot_sk,
            encode(gen_random_bytes(32), 'hex'),
            (3 + random() * 200)::INTEGER,
            created_ts + INTERVAL '20 minutes',
            created_ts
        )
        ON CONFLICT DO NOTHING;

        mint_id := 'mnt_' || substr(encode(gen_random_bytes(4), 'hex'), 1, 8);
        INSERT INTO mints (id, vault_id, ubtc_amount, btc_price_usd, collateral_ratio, status, created_at)
        VALUES (mint_id, vault_id, ubtc_minted::TEXT,
                (btc_price * (0.92 + random() * 0.16))::TEXT,
                round((1.5 + random() * 0.6)::NUMERIC, 2)::TEXT,
                'active', created_ts + INTERVAL '25 minutes')
        ON CONFLICT DO NOTHING;

        FOR j IN 1..(1 + (random() * 4)::INTEGER) LOOP
            IF random() < 0.40 THEN
                mint_amt := round((ubtc_minted * (0.05 + random() * 0.20))::NUMERIC, 2);
                INSERT INTO mints (id, vault_id, ubtc_amount, btc_price_usd, collateral_ratio, status, created_at)
                VALUES ('mnt_' || substr(encode(gen_random_bytes(4), 'hex'), 1, 8),
                        vault_id, mint_amt::TEXT,
                        (btc_price * (0.92 + random() * 0.16))::TEXT,
                        round((1.5 + random() * 0.6)::NUMERIC, 2)::TEXT,
                        'active',
                        created_ts + (j * INTERVAL '7 days') + (random() * INTERVAL '6 hours'))
                ON CONFLICT DO NOTHING;
            ELSIF random() < 0.65 THEN
                burn_amt := round((ubtc_minted * (0.02 + random() * 0.15))::NUMERIC, 2);
                burn_id  := 'burn_' || substr(encode(gen_random_bytes(4), 'hex'), 1, 8);
                INSERT INTO burns (id, vault_id, ubtc_burned, btc_released_sats, kind, created_at)
                VALUES (burn_id, vault_id, burn_amt::TEXT,
                        (burn_amt / btc_price * 1e8)::BIGINT, 'partial',
                        created_ts + (j * INTERVAL '11 days') + (random() * INTERVAL '6 hours'))
                ON CONFLICT DO NOTHING;
            ELSE
                burn_amt := round((ubtc_minted * (0.01 + random() * 0.10))::NUMERIC, 2);
                transfer_id := 'txfr_' || substr(encode(gen_random_bytes(4), 'hex'), 1, 8);
                INSERT INTO ubtc_transfers (id, from_vault_id, to_address, ubtc_amount, status, created_at)
                VALUES (transfer_id, vault_id,
                        'ubtc1' || substr(encode(gen_random_bytes(16), 'hex'), 1, 32),
                        burn_amt::TEXT, 'completed',
                        created_ts + (j * INTERVAL '5 days') + (random() * INTERVAL '6 hours'))
                ON CONFLICT DO NOTHING;
                INSERT INTO burns (id, vault_id, ubtc_burned, kind, created_at)
                VALUES ('burn_' || substr(encode(gen_random_bytes(4), 'hex'), 1, 8),
                        vault_id, burn_amt::TEXT, 'transfer',
                        created_ts + (j * INTERVAL '5 days') + (random() * INTERVAL '6 hours'))
                ON CONFLICT DO NOTHING;

                proof_id    := 'prf_' || substr(encode(gen_random_bytes(6), 'hex'), 1, 12);
                proof_db_id := 'proof_' || substr(encode(gen_random_bytes(4), 'hex'), 1, 8);
                INSERT INTO ubtc_proofs (id, proof_id, sender_vault_id, recipient_wallet_address, proof_data, created_at)
                VALUES (proof_db_id, proof_id, vault_id,
                        'ubtc1' || substr(encode(gen_random_bytes(16), 'hex'), 1, 32),
                        jsonb_build_object(
                            'version', 'UBTCV1',
                            'proof_id', proof_id,
                            'created_at', extract(epoch from created_ts)::INTEGER,
                            'ownership', jsonb_build_object('ubtc_amount', burn_amt::TEXT),
                            'collateral', jsonb_build_object('vault_id', vault_id)
                        ),
                        created_ts + (j * INTERVAL '5 days') + (random() * INTERVAL '6 hours'))
                ON CONFLICT DO NOTHING;
                INSERT INTO seeded_identifiers (kind, value) VALUES ('proof_id', proof_id);
            END IF;
        END LOOP;

        IF random() < 0.35 THEN
            nullifier_id  := 'null_' || substr(encode(gen_random_bytes(4), 'hex'), 1, 8);
            nullifier_hex := encode(gen_random_bytes(32), 'hex');
            INSERT INTO nullifiers (id, nullifier_hex, bitcoin_txid, spent_at)
            VALUES (nullifier_id, nullifier_hex,
                    encode(gen_random_bytes(32), 'hex'),
                    created_ts + INTERVAL '30 days' + (random() * INTERVAL '14 days'))
            ON CONFLICT DO NOTHING;
        END IF;

        INSERT INTO seeded_identifiers (kind, value) VALUES ('vault_id',       vault_id);
        INSERT INTO seeded_identifiers (kind, value) VALUES ('wallet_address', wallet_addr);
        INSERT INTO seeded_identifiers (kind, value) VALUES ('username',       username);
    END LOOP;
END
$seed$;

-- After running this file, immediately:
--   \copy seeded_identifiers TO '/path/off/host/watchlist.txt' CSV
-- then:
--   DROP TABLE seeded_identifiers;
-- so the edge DB itself does not store a copy of the watchlist.
